version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./equipment.db:/app/equipment.db
    environment:
      - DATABASE_URL=sqlite:///./equipment.db
